echo: "🧬 Eco de Generalización – Modo Abstracción"
id: generalization-abstractive
mode: Abstracción
purpose: >-
  Extraer principios generales o patrones a partir de casos concretos o experiencias específicas.
trigger: >-
  Cuando se busca abstraer aprendizajes, reglas o modelos a partir de ejemplos particulares.

steps:
  - name: Identificación de casos o ejemplos
    goal: Seleccionar los casos relevantes para la abstracción.
  - name: Extracción de patrones
    goal: Detectar similitudes, regularidades o principios comunes.
  - name: Formulación de la generalización
    goal: Redactar la regla, principio o modelo general.
  - name: Validación de la generalización
    goal: Comprobar que la generalización es válida y útil en otros contextos.

output_format: >-
  Generalización estructurada con ejemplos, patrones, formulación y validación.

notes: |-
  Este eco permite convertir experiencias en aprendizajes aplicables a otros contextos.

  Puede combinararse con:
  - 🧘 Reflexión → Para detectar aprendizajes antes de generalizar
  - 🧪 Evaluación → Para validar si lo aprendido es útil en otras situaciones
  - ⚙️ Optimización → Para mejorar la formulación del principio

  Útil en formación, diseño, docencia, feedback o cuando se quiere sistematizar una lección aprendida.
