# 🧭 Eco de Planificación – Modo Formativo (V4 – Secuencia corregida y sin reactivación)
echo: Eco de Planificación – Modo Formativo
id: planning-formative
mode: Formative
purpose: >-
  Planificar un proceso de aprendizaje, desarrollo o implementación paso a paso, asegurando claridad,
  adaptación al contexto y retroalimentación. Este eco guía la construcción de roadmaps estructurados para
  individuos, equipos o proyectos.
trigger: >-
  Cuando el usuario quiere aprender algo, organizar una tarea compleja, estructurar un camino de mejora o
  diseñar un plan de acción claro.
config:
  retry_on_fail: true
  max_retries_per_step: 3
steps:
  - name: Clarificación del objetivo final
    goal: Determinar con precisión qué se quiere lograr al final del proceso.
    validation:
      - ¿Se identificó un resultado o entregable específico?
      - ¿Se expresa en términos concretos y medibles?
    expected_output: Frase o párrafo que defina claramente el objetivo del plan

  - name: Recolección activa de información contextual
    goal: Asegurar que se dispone de toda la información relevante antes de planificar.
    actions:
      - Formular preguntas al usuario para obtener:
          - Nivel de conocimiento actual (si es un proceso de aprendizaje)
          - Recursos disponibles (tiempo, equipo, herramientas)
          - Restricciones técnicas o de calendario
          - Expectativas externas (clientes, stakeholders)
          - Antecedentes relevantes (intentos anteriores, decisiones tomadas)
    critical_instruction: No continuar al siguiente paso si hay información clave faltante.
    validation:
      - ¿Se formularon todas las preguntas clave?
      - ¿Se documentó toda la información relevante?
      - ¿Se detuvo el flujo si faltaba información?
    expected_output: Mapa de contexto estructurado con respuestas del usuario, recursos, restricciones y antecedentes

  - name: Diagnóstico del punto de partida
    goal: Evaluar dónde está el usuario o sistema ahora en relación al objetivo planteado.
    validation:
      - ¿Se reconoció el estado actual con suficiente detalle?
      - ¿Se identificaron brechas con respecto al objetivo?
    expected_output: Diagnóstico de situación actual con fortalezas y áreas a mejorar

  - name: Definición de rol del aprendiz o actor principal
    goal: Adaptar el plan a quien lo va a ejecutar, considerando sus capacidades y estilo.
    validation:
      - ¿Se describió el sujeto del plan?
      - ¿Se consideraron nivel, disponibilidad, estilo o limitaciones?
    expected_output: Perfil resumido del ejecutor (persona, equipo, IA, etc.)

  - name: Detección de obstáculos posibles
    goal: Prever qué podría interferir con el progreso y cómo manejarlo.
    validation:
      - ¿Se identificaron bloqueos potenciales (técnicos, motivacionales, de tiempo)?
      - ¿Se propusieron estrategias de prevención o mitigación?
    expected_output: Lista de obstáculos + plan preventivo o de contención

  - name: Definición del entregable final
    goal: Establecer cuál será el producto, habilidad o conocimiento adquirido.
    validation:
      - ¿Está alineado con el objetivo inicial?
      - ¿Es demostrable, evaluable o compartible?
    expected_output: Descripción del resultado final esperado

  - name: División en módulos de ejecución
    goal: >-
      Dividir el camino hacia el objetivo en acciones específicas, con lógica secuencial, que surjan directamente
      del análisis previo del objetivo, contexto, obstáculos, capacidades y entregables.
    validation:
      - ¿Cada módulo representa una acción ejecutiva basada en la información recolectada?
      - ¿Tiene un propósito operativo claro y medible?
      - ¿Incluye su justificación contextual y su vínculo lógico con el resto del proceso?
    expected_output: >-
      Tabla estructurada con los siguientes campos por módulo:
        - name
        - purpose (acción concreta)
        - context_description (por qué debe hacerse y qué aporta)
        - deliverables
        - dependencies
  - name: Visualización del progreso + Adaptación dinámica
      goal: Definir cómo se medirá el avance y cómo se adaptará el plan.
      validation:
        - ¿Se definieron señales o métricas de avance?
        - ¿Se incluyó un mecanismo de ajuste dinámico?
      expected_output: >-
        Sistema de seguimiento compuesto por:
          - Lista de indicadores por módulo
          - Frecuencia de revisión
          - Formato de seguimiento (dashboard, checklist, tabla, log de ejecución)
          - Criterios para adaptar el plan si hay desvíos
output_format: >-
  Roadmap estructurado en formato serializable (YAML o Markdown) con tabla de módulos (name, purpose, context_description,
  deliverables, dependencies), puntos críticos, y estrategia de seguimiento y adaptación.

notes: |-
  Esta versión optimizada mejora la trazabilidad en flujos de IA mediante el uso de descripciones contextuales por módulo y un formato estructurado.
  Es especialmente útil para ejecuciones distribuidas, asincrónicas o progresivas. Puede combinarse con:
  - 🧪 Eco de Evaluación para validar la consistencia entre módulos
  - ✅ Eco de Coherencia para asegurar la alineación con el objetivo general
  - 🔁 Eco de Ejecución para ejecutar cada módulo de forma independiente y validable
  - 🧩 Eco de Orquestación para conectar múltiples módulos en un flujo cognitivo completo
  Se recomienda serializar cada módulo con las claves: name, purpose, context_description, deliverables, dependencies.