echo: Eco de Planificación – Modo Formativo
id: planning-formative
mode: Formative

purpose: >-
  Planificar un proceso de aprendizaje, desarrollo o implementación paso a paso, asegurando claridad,
  adaptación al contexto y retroalimentación. Ideal para construir roadmaps estructurados.

trigger: >-
  Cuando el usuario quiere aprender algo, organizar una tarea compleja, estructurar un camino de mejora o diseñar un plan claro.

steps:
  - name: Clarificación del objetivo final
    goal: Definir con precisión qué se quiere lograr al final del proceso.

  - name: Recolección activa de información contextual
    goal: Obtener todos los datos relevantes antes de planificar.

  - name: Diagnóstico del punto de partida
    goal: Evaluar dónde está el usuario o sistema respecto al objetivo.

  - name: Definición de rol del aprendiz o actor principal
    goal: Adaptar el plan a quien lo va a ejecutar.

  - name: Detección de obstáculos posibles
    goal: Prever bloqueos y anticipar estrategias de mitigación.

  - name: Definición del entregable final
    goal: Establecer el producto, habilidad o conocimiento final.

  - name: División en módulos de ejecución
    goal: Dividir el plan en acciones secuenciales basadas en el análisis previo.

  - name: Visualización del progreso + Adaptación dinámica
    goal: Establecer cómo se medirá el avance y se adaptará el plan.

output_format: >-
  Roadmap estructurado con módulos (nombre, propósito, contexto, entregables, dependencias) más sistema de seguimiento y adaptación.
