echo: "✅ Eco de Coherencia – Modo Autocorrección"
id: coherence-self-correction
mode: Autocorrección
purpose: >-
  Detectar si se perdió el propósito o dirección del flujo, corregir desviaciones y retomar desde el punto correcto.
  Este eco ayuda a identificar y corregir contradicciones, bucles innecesarios o desalineaciones, y guía el flujo de vuelta a su objetivo.

trigger: >-
  Cuando se detecta una contradicción, repetición innecesaria o desalineación con el objetivo original.

config:
  retry_on_fail: true
  max_retries_per_step: 2

steps:
  - name: Verificación de alineación con el propósito
    goal: Comparar el estado actual con el propósito original o roadmap.
    validation:
      - ¿Se recuperó o infirió el propósito?
      - ¿Se evaluó si el estado actual responde a ese propósito?
    expected_output: Diagnóstico de alineación o desviación

  - name: Detección de desviaciones, bucles o contradicciones
    goal: Identificar repeticiones, contradicciones internas o pérdida de foco.
    validation:
      - ¿Se describió claramente la desviación?
      - ¿Se identificó la diferencia entre repetición y contradicción?
    expected_output: Descripción del problema detectado

  - name: Punto válido de reanudación
    goal: Definir desde qué paso o reformulación debe continuar el proceso.
    validation:
      - ¿Se propuso un punto de reanudación concreto y justificable?
      - ¿Está relacionado con el propósito o contexto original?
    expected_output: Punto de reanudación sugerido + justificación

  - name: Corrección estructurada del flujo
    goal: Retomar el proceso desde el punto correcto, explícitamente, respetando las restricciones.
    validation:
      - ¿Se aplicó una corrección clara?
      - ¿Se explicaron los motivos del ajuste?
    expected_output: Reformulación del input o decisión validada

  - name: Reactivación validada del proceso con nuevo input
    goal: Confirmar con el usuario (o sistema) que el nuevo punto de partida es válido y activar el flujo desde allí.
    validation:
      - ¿El usuario aceptó la corrección?
      - ¿El nuevo input está listo para ejecutarse?
    expected_output: Input corregido validado y listo como nuevo paso

output_format: >-
  Corrección estructurada del flujo, con diagnóstico de la desviación, punto de reanudación, reformulación validada y reactivación desde una base coherente.

notes: |-
  Este eco puede activarse automáticamente ante bucles o contradicciones.
  Es compatible con los ecos de Evaluación, Diagnóstico, Planificación y Reflexión.
