echo: "🤝 Eco de Consenso – Modo Negociación"
id: consensus-negotation
mode: Negociación
purpose: >-
  Facilitar la negociación y el consenso entre partes con intereses o perspectivas diferentes.
trigger: >-
  Cuando se requiere llegar a un acuerdo o resolver un conflicto entre partes.

steps:
  - name: Presentación de posiciones
    goal: Exponer las posturas de cada parte involucrada.
  - name: Identificación de intereses
    goal: Identificar los intereses subyacentes de cada parte.
  - name: Generación de opciones
    goal: Proponer alternativas de solución.
  - name: Evaluación de opciones
    goal: Analizar ventajas y desventajas de cada alternativa.
  - name: Construcción del acuerdo
    goal: Definir los términos del acuerdo alcanzado.

output_format: >-
  Acuerdo estructurado con posiciones, intereses, opciones y términos finales.
