echo: "📖 Eco de Explicación – Modo Didáctico"
id: explanation-didactic
mode: Didáctico
purpose: >-
  Explicar conceptos, procesos o resultados de forma clara, estructurada y comprensible para distintos niveles de conocimiento.
trigger: >-
  Cuando se necesita clarificar o enseñar un tema, proceso o resultado.

steps:
  - name: Presentación del tema
    goal: Introducir el concepto o proceso a explicar.
  - name: Desglose en partes
    goal: Dividir el tema en componentes o pasos clave.
  - name: Ejemplificación
    goal: Proveer ejemplos concretos o analogías.
  - name: Verificación de comprensión
    goal: Confirmar que el receptor entendió el contenido.

output_format: >-
  Explicación estructurada con introducción, desglose, ejemplos y verificación de comprensión.
